## 1. Import packeges

In [0]:
%pip install h5py

Requirement already satisfied: h5py in /local_disk0/.ephemeral_nfs/envs/pythonEnv-653a3a9d-2283-445c-981d-2e907aec10ff/lib/python3.12/site-packages (3.13.0)
Requirement already satisfied: numpy>=1.19.3 in /databricks/python3/lib/python3.12/site-packages (from h5py) (1.26.4)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
import h5py
import os
import pandas as pd
import numpy as np
import datetime
import scipy

In [0]:
adapt_path = '/dbfs/mnt/thesis/input_data/adapt/'
train_path = '/dbfs/mnt/thesis/input_data/train/'

output_path = '/dbfs/mnt/thesis/output_data/'

## 2. Load the data
- Explore the input file structure
- Load the adapt data to dataframe
- Load the train data to dataframe
- Concatenate together and sort by Datetime

In [0]:
# Check one .h5 file structure
def print_it(name):
    dset = f[name]
    print(dset)
    print(type(dset))

with h5py.File(train_path + 'X1.h5', 'r') as f:
    f.visit(print_it)

<HDF5 group "/X" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S14">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value" (5 members)>
<class 'h5py._hl.group.Group'>
<HDF5 group "/X/value/X" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S13">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (231, 1916, 1), type "<f4">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/aux" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S7">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (2,), type "<i4">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/hat" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S14">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/hat/value" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 group "/X/value/hat/value/X" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S7">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (2,), type "<i4">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/hat/value/t" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S7">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (2,), type "<i4">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/metadata" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S7">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (2,), type "<i4">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 group "/X/value/t" (2 members)>
<class 'h5py._hl.group.Group'>
<HDF5 dataset "type": shape (), type "|S7">
<class 'h5py._hl.dataset.Dataset'>
<HDF5 dataset "value": shape (231, 1), type "<f8">
<class 'h5py._hl.dataset.Dataset'>

In [0]:
#get the input files list
adapt_input_files = os.listdir(adapt_path)
train_input_files = os.listdir(train_path)

### Load the data from the adapt folder

In [0]:

adapt_result_df = pd.DataFrame()

#iterate through the input files
for h_file in adapt_input_files:
    print("Actual:", h_file)
    curr_result_df = pd.DataFrame()
    with h5py.File(adapt_path + h_file, 'r') as f:
        #get the values from the h5 file
        val_data = f.get('X/value/X/value')
        val_dataset = np.array(val_data)
        reshaped_val_dataset = val_dataset.reshape(val_dataset.shape[0], val_dataset.shape[1])
        # print("VAL_SHAPE:", reshaped_val_dataset.shape)
        curr_value_df = pd.DataFrame(reshaped_val_dataset)
        
        #get the timestamps from the h5 file
        time_data = f.get('X/value/t/value')
        time_dataset = np.array(time_data)
        # print("TIME SHAPE:", time_dataset.shape)
        curr_time_df = pd.DataFrame(time_dataset, columns=['DATETIME'])

    #concatenate together
    curr_result_df = pd.concat([curr_time_df,curr_value_df],axis=1)
    adapt_result_df = pd.concat([adapt_result_df,curr_result_df],axis=0)
    print("Shape final:", adapt_result_df.shape)

Actual: X0.h5
Shape final: (12, 1917)
Actual: X1.h5
Shape final: (24, 1917)
Actual: X10.h5
Shape final: (36, 1917)
Actual: X11.h5
Shape final: (940, 1917)
Actual: X12.h5
Shape final: (952, 1917)
Actual: X13.h5
Shape final: (964, 1917)
Actual: X14.h5
Shape final: (3091, 1917)
Actual: X15.h5
Shape final: (3103, 1917)
Actual: X16.h5
Shape final: (3115, 1917)
Actual: X17.h5
Shape final: (4235, 1917)
Actual: X18.h5
Shape final: (4247, 1917)
Actual: X19.h5
Shape final: (4259, 1917)
Actual: X2.h5
Shape final: (5576, 1917)
Actual: X20.h5
Shape final: (6714, 1917)
Actual: X21.h5
Shape final: (6726, 1917)
Actual: X22.h5
Shape final: (6738, 1917)
Actual: X23.h5
Shape final: (8218, 1917)
Actual: X24.h5
Shape final: (8230, 1917)
Actual: X25.h5
Shape final: (8242, 1917)
Actual: X26.h5
Shape final: (8382, 1917)
Actual: X27.h5
Shape final: (8394, 1917)
Actual: X28.h5
Shape final: (8406, 1917)
Actual: X29.h5
Shape final: (9212, 1917)
Actual: X3.h5
Shape final: (9224, 1917)
Actual: X30.h5
Shape final: (9236, 1917)
Actual: X31.h5
Shape final: (9248, 1917)
Actual: X32.h5
Shape final: (12271, 1917)
Actual: X33.h5
Shape final: (12283, 1917)
Actual: X34.h5
Shape final: (12295, 1917)
Actual: X35.h5
Shape final: (12553, 1917)
Actual: X36.h5
Shape final: (12565, 1917)
Actual: X37.h5
Shape final: (12577, 1917)
Actual: X38.h5
Shape final: (15181, 1917)
Actual: X39.h5
Shape final: (15193, 1917)
Actual: X4.h5
Shape final: (15205, 1917)
Actual: X40.h5
Shape final: (15217, 1917)
Actual: X41.h5
Shape final: (15890, 1917)
Actual: X42.h5
Shape final: (15902, 1917)
Actual: X43.h5
Shape final: (15914, 1917)
Actual: X44.h5
Shape final: (16397, 1917)
Actual: X45.h5
Shape final: (16409, 1917)
Actual: X46.h5
Shape final: (16421, 1917)
Actual: X47.h5
Shape final: (17315, 1917)
Actual: X48.h5
Shape final: (17327, 1917)
Actual: X49.h5
Shape final: (17339, 1917)
Actual: X5.h5
Shape final: (17503, 1917)
Actual: X50.h5
Shape final: (17783, 1917)
Actual: X51.h5
Shape final: (17795, 1917)
Actual: X52.h5
Shape final: (17807, 1917)
Actual: X53.h5
Shape final: (18006, 1917)
Actual: X54.h5
Shape final: (18018, 1917)
Actual: X55.h5
Shape final: (18030, 1917)
Actual: X56.h5
Shape final: (19001, 1917)
Actual: X57.h5
Shape final: (19013, 1917)
Actual: X58.h5
Shape final: (19025, 1917)
Actual: X59.h5
Shape final: (19340, 1917)
Actual: X6.h5
Shape final: (19352, 1917)
Actual: X60.h5
Shape final: (19364, 1917)
Actual: X61.h5
Shape final: (19376, 1917)
Actual: X62.h5
Shape final: (20248, 1917)
Actual: X63.h5
Shape final: (20260, 1917)
Actual: X64.h5
Shape final: (20272, 1917)
Actual: X65.h5
Shape final: (22331, 1917)
Actual: X66.h5
Shape final: (22343, 1917)
Actual: X67.h5
Shape final: (22355, 1917)
Actual: X68.h5
Shape final: (24238, 1917)
Actual: X7.h5
Shape final: (24250, 1917)
Actual: X8.h5
Shape final: (24807, 1917)
Actual: X9.h5
Shape final: (24819, 1917)

In [0]:
#format the date and sort the data
adapt_result_df['DATETIME'] = pd.to_datetime(adapt_result_df['DATETIME'], unit='s')
adapt_result_df = adapt_result_df.sort_values(['DATETIME'])
adapt_result_df.reset_index(drop=True,inplace=True)

In [0]:
#Check the result
print("Adapt start:", adapt_result_df['DATETIME'].min(), "Adapt end:", adapt_result_df['DATETIME'].max())
adapt_result_df.head(5)

Adapt start: 2010-07-01 18:05:00 Adapt end: 2010-09-25 22:15:00

             DATETIME           0          1    2  ...  1912  1913  1914  1915
0 2010-07-01 18:05:00  342.600006 -72.300003  0.0  ...   0.0   0.0   0.0   0.0
1 2010-07-01 18:10:00  340.519989 -77.459999  0.0  ...   0.0   0.0   0.0   0.0
2 2010-07-01 18:15:00  332.220001 -84.269997  0.0  ...   0.0   0.0   0.0   0.0
3 2010-07-01 18:20:00  323.000000 -74.360001  0.0  ...   0.0   0.0   0.0   0.0
4 2010-07-01 18:25:00  302.429993 -88.839996  0.0  ...   0.0   0.0   0.0   0.0

[5 rows x 1917 columns]

### Load the data from the train folder

In [0]:
train_result_df = pd.DataFrame()

#iterate through the input files
for h_file in train_input_files:
    print("Actual:", h_file)
    curr_result_df = pd.DataFrame()
    with h5py.File(train_path + h_file, 'r') as f:
        #get the values from the h5 file
        val_data = f.get('X/value/X/value')
        val_dataset = np.array(val_data)
        reshaped_val_dataset = val_dataset.reshape(val_dataset.shape[0], val_dataset.shape[1])
        # print("VAL_SHAPE:", reshaped_val_dataset.shape)
        curr_value_df = pd.DataFrame(reshaped_val_dataset)
        
        #get the timestamps from the h5 file
        time_data = f.get('X/value/t/value')
        time_dataset = np.array(time_data)
        # print("TIME SHAPE:", time_dataset.shape)
        curr_time_df = pd.DataFrame(time_dataset, columns=['DATETIME'])

    #concatenate together
    curr_result_df = pd.concat([curr_time_df,curr_value_df],axis=1)
    train_result_df = pd.concat([train_result_df,curr_result_df],axis=0)
    print("Shape final:", train_result_df.shape)

Actual: X1.h5
Shape final: (231, 1917)
Actual: X10.h5
Shape final: (3273, 1917)
Actual: X100.h5
Shape final: (3549, 1917)
Actual: X101.h5
Shape final: (3561, 1917)
Actual: X102.h5
Shape final: (3573, 1917)
Actual: X103.h5
Shape final: (4325, 1917)
Actual: X104.h5
Shape final: (4337, 1917)
Actual: X105.h5
Shape final: (4349, 1917)
Actual: X106.h5
Shape final: (7646, 1917)
Actual: X107.h5
Shape final: (7658, 1917)
Actual: X108.h5
Shape final: (7670, 1917)
Actual: X109.h5
Shape final: (8773, 1917)
Actual: X11.h5
Shape final: (8785, 1917)
Actual: X110.h5
Shape final: (8797, 1917)
Actual: X111.h5
Shape final: (8809, 1917)
Actual: X112.h5
Shape final: (9637, 1917)
Actual: X113.h5
Shape final: (9649, 1917)
Actual: X114.h5
Shape final: (9661, 1917)
Actual: X115.h5
Shape final: (10720, 1917)
Actual: X116.h5
Shape final: (10732, 1917)
Actual: X117.h5
Shape final: (10744, 1917)
Actual: X118.h5
Shape final: (11651, 1917)
Actual: X119.h5
Shape final: (11663, 1917)
Actual: X12.h5
Shape final: (11675, 1917)
Actual: X120.h5
Shape final: (11687, 1917)
Actual: X121.h5
Shape final: (12293, 1917)
Actual: X122.h5
Shape final: (12305, 1917)
Actual: X123.h5
Shape final: (12317, 1917)
Actual: X124.h5
Shape final: (12551, 1917)
Actual: X125.h5
Shape final: (12563, 1917)
Actual: X126.h5
Shape final: (12575, 1917)
Actual: X127.h5
Shape final: (15011, 1917)
Actual: X128.h5
Shape final: (15023, 1917)
Actual: X129.h5
Shape final: (15035, 1917)
Actual: X13.h5
Shape final: (15971, 1917)
Actual: X130.h5
Shape final: (16597, 1917)
Actual: X131.h5
Shape final: (16609, 1917)
Actual: X132.h5
Shape final: (16621, 1917)
Actual: X133.h5
Shape final: (18340, 1917)
Actual: X134.h5
Shape final: (18352, 1917)
Actual: X135.h5
Shape final: (18364, 1917)
Actual: X136.h5
Shape final: (18541, 1917)
Actual: X137.h5
Shape final: (18553, 1917)
Actual: X138.h5
Shape final: (18565, 1917)
Actual: X139.h5
Shape final: (19705, 1917)
Actual: X14.h5
Shape final: (19717, 1917)
Actual: X140.h5
Shape final: (19729, 1917)
Actual: X141.h5
Shape final: (19741, 1917)
Actual: X142.h5
Shape final: (20805, 1917)
Actual: X143.h5
Shape final: (20817, 1917)
Actual: X144.h5
Shape final: (20829, 1917)
Actual: X145.h5
Shape final: (24258, 1917)
Actual: X146.h5
Shape final: (24270, 1917)
Actual: X147.h5
Shape final: (24282, 1917)
Actual: X148.h5
Shape final: (24670, 1917)
Actual: X149.h5
Shape final: (24682, 1917)
Actual: X15.h5
Shape final: (24694, 1917)
Actual: X150.h5
Shape final: (24706, 1917)
Actual: X151.h5
Shape final: (25414, 1917)
Actual: X152.h5
Shape final: (25426, 1917)
Actual: X153.h5
Shape final: (25438, 1917)
Actual: X154.h5
Shape final: (26368, 1917)
Actual: X155.h5
Shape final: (26380, 1917)
Actual: X156.h5
Shape final: (26392, 1917)
Actual: X157.h5
Shape final: (26678, 1917)
Actual: X158.h5
Shape final: (26690, 1917)
Actual: X159.h5
Shape final: (26702, 1917)
Actual: X16.h5
Shape final: (27624, 1917)
Actual: X160.h5
Shape final: (29033, 1917)
Actual: X161.h5
Shape final: (29045, 1917)
Actual: X162.h5
Shape final: (29057, 1917)
Actual: X163.h5
Shape final: (31368, 1917)
Actual: X164.h5
Shape final: (31380, 1917)
Actual: X165.h5
Shape final: (31392, 1917)
Actual: X166.h5
Shape final: (31488, 1917)
Actual: X167.h5
Shape final: (31500, 1917)
Actual: X168.h5
Shape final: (31512, 1917)
Actual: X169.h5
Shape final: (31655, 1917)
Actual: X17.h5
Shape final: (31667, 1917)
Actual: X170.h5
Shape final: (31679, 1917)
Actual: X171.h5
Shape final: (31691, 1917)
Actual: X172.h5
Shape final: (32926, 1917)
Actual: X173.h5
Shape final: (32938, 1917)
Actual: X174.h5
Shape final: (32950, 1917)
Actual: X175.h5
Shape final: (33290, 1917)
Actual: X176.h5
Shape final: (33302, 1917)
Actual: X177.h5
Shape final: (33314, 1917)
Actual: X178.h5
Shape final: (33930, 1917)
Actual: X179.h5
Shape final: (33942, 1917)
Actual: X18.h5
Shape final: (33954, 1917)
Actual: X180.h5
Shape final: (33966, 1917)
Actual: X181.h5
Shape final: (35439, 1917)
Actual: X182.h5
Shape final: (35451, 1917)
Actual: X183.h5
Shape final: (35463, 1917)
Actual: X184.h5
Shape final: (36198, 1917)
Actual: X185.h5
Shape final: (36210, 1917)
Actual: X186.h5
Shape final: (36222, 1917)
Actual: X187.h5
Shape final: (36380, 1917)
Actual: X188.h5
Shape final: (36392, 1917)
Actual: X189.h5
Shape final: (36404, 1917)
Actual: X19.h5
Shape final: (36796, 1917)
Actual: X190.h5
Shape final: (38717, 1917)
Actual: X191.h5
Shape final: (38729, 1917)
Actual: X192.h5
Shape final: (38741, 1917)
Actual: X193.h5
Shape final: (40496, 1917)
Actual: X194.h5
Shape final: (40508, 1917)
Actual: X195.h5
Shape final: (40520, 1917)
Actual: X196.h5
Shape final: (41181, 1917)
Actual: X197.h5
Shape final: (41193, 1917)
Actual: X198.h5
Shape final: (41205, 1917)
Actual: X199.h5
Shape final: (41631, 1917)
Actual: X2.h5
Shape final: (41643, 1917)
Actual: X20.h5
Shape final: (41655, 1917)
Actual: X200.h5
Shape final: (41667, 1917)
Actual: X201.h5
Shape final: (41679, 1917)
Actual: X202.h5
Shape final: (42312, 1917)
Actual: X203.h5
Shape final: (42324, 1917)
Actual: X204.h5
Shape final: (42336, 1917)
Actual: X205.h5
Shape final: (43173, 1917)
Actual: X206.h5
Shape final: (43185, 1917)
Actual: X207.h5
Shape final: (43197, 1917)
Actual: X208.h5
Shape final: (45730, 1917)
Actual: X209.h5
Shape final: (45742, 1917)
Actual: X21.h5
Shape final: (45754, 1917)
Actual: X210.h5
Shape final: (45766, 1917)
Actual: X211.h5
Shape final: (46333, 1917)
Actual: X212.h5
Shape final: (46345, 1917)
Actual: X213.h5
Shape final: (46357, 1917)
Actual: X214.h5
Shape final: (47059, 1917)
Actual: X215.h5
Shape final: (47071, 1917)
Actual: X216.h5
Shape final: (47083, 1917)
Actual: X217.h5
Shape final: (49874, 1917)
Actual: X218.h5
Shape final: (49886, 1917)
Actual: X219.h5
Shape final: (49898, 1917)
Actual: X22.h5
Shape final: (50803, 1917)
Actual: X220.h5
Shape final: (51181, 1917)
Actual: X221.h5
Shape final: (51193, 1917)
Actual: X222.h5
Shape final: (51205, 1917)
Actual: X223.h5
Shape final: (51882, 1917)
Actual: X224.h5
Shape final: (51894, 1917)
Actual: X225.h5
Shape final: (51906, 1917)
Actual: X226.h5
Shape final: (52796, 1917)
Actual: X227.h5
Shape final: (52808, 1917)
Actual: X228.h5
Shape final: (52820, 1917)
Actual: X229.h5
Shape final: (52983, 1917)
Actual: X23.h5
Shape final: (52995, 1917)
Actual: X230.h5
Shape final: (53007, 1917)
Actual: X231.h5
Shape final: (53019, 1917)
Actual: X232.h5
Shape final: (54162, 1917)
Actual: X233.h5
Shape final: (54174, 1917)
Actual: X234.h5
Shape final: (54186, 1917)
Actual: X235.h5
Shape final: (57976, 1917)
Actual: X236.h5
Shape final: (57988, 1917)
Actual: X237.h5
Shape final: (58000, 1917)
Actual: X238.h5
Shape final: (58199, 1917)
Actual: X239.h5
Shape final: (58211, 1917)
Actual: X24.h5
Shape final: (58223, 1917)
Actual: X240.h5
Shape final: (58235, 1917)
Actual: X241.h5
Shape final: (58703, 1917)
Actual: X242.h5
Shape final: (58715, 1917)
Actual: X243.h5
Shape final: (58727, 1917)
Actual: X244.h5
Shape final: (59056, 1917)
Actual: X245.h5
Shape final: (59068, 1917)
Actual: X246.h5
Shape final: (59080, 1917)
Actual: X247.h5
Shape final: (59108, 1917)
Actual: X248.h5
Shape final: (59120, 1917)
Actual: X249.h5
Shape final: (59132, 1917)
Actual: X25.h5
Shape final: (62136, 1917)
Actual: X250.h5
Shape final: (63275, 1917)
Actual: X251.h5
Shape final: (63287, 1917)
Actual: X252.h5
Shape final: (63299, 1917)
Actual: X253.h5
Shape final: (64289, 1917)
Actual: X254.h5
Shape final: (64301, 1917)
Actual: X255.h5
Shape final: (64313, 1917)
Actual: X256.h5
Shape final: (65730, 1917)
Actual: X257.h5
Shape final: (65742, 1917)
Actual: X258.h5
Shape final: (65754, 1917)
Actual: X259.h5
Shape final: (66931, 1917)
Actual: X26.h5
Shape final: (66943, 1917)
Actual: X260.h5
Shape final: (66955, 1917)
Actual: X261.h5
Shape final: (66967, 1917)
Actual: X262.h5
Shape final: (67239, 1917)
Actual: X263.h5
Shape final: (67251, 1917)
Actual: X264.h5
Shape final: (67263, 1917)
Actual: X265.h5
Shape final: (71390, 1917)
Actual: X266.h5
Shape final: (71402, 1917)
Actual: X267.h5
Shape final: (71414, 1917)
Actual: X268.h5
Shape final: (73078, 1917)
Actual: X269.h5
Shape final: (73090, 1917)
Actual: X27.h5
Shape final: (73102, 1917)
Actual: X270.h5
Shape final: (73114, 1917)
Actual: X271.h5
Shape final: (73294, 1917)
Actual: X272.h5
Shape final: (73306, 1917)
Actual: X273.h5
Shape final: (73318, 1917)
Actual: X274.h5
Shape final: (73387, 1917)
Actual: X275.h5
Shape final: (73399, 1917)
Actual: X276.h5
Shape final: (73411, 1917)
Actual: X277.h5
Shape final: (74056, 1917)
Actual: X278.h5
Shape final: (74068, 1917)
Actual: X279.h5
Shape final: (74080, 1917)
Actual: X28.h5
Shape final: (75995, 1917)
Actual: X280.h5
Shape final: (78117, 1917)
Actual: X281.h5
Shape final: (78129, 1917)
Actual: X282.h5
Shape final: (78141, 1917)
Actual: X283.h5
Shape final: (79520, 1917)
Actual: X284.h5
Shape final: (79532, 1917)
Actual: X285.h5
Shape final: (79544, 1917)
Actual: X286.h5
Shape final: (80263, 1917)
Actual: X287.h5
Shape final: (80275, 1917)
Actual: X288.h5
Shape final: (80287, 1917)
Actual: X289.h5
Shape final: (81303, 1917)
Actual: X29.h5
Shape final: (81315, 1917)
Actual: X3.h5
Shape final: (81327, 1917)
Actual: X30.h5
Shape final: (81339, 1917)
Actual: X31.h5
Shape final: (82638, 1917)
Actual: X32.h5
Shape final: (82650, 1917)
Actual: X33.h5
Shape final: (82662, 1917)
Actual: X34.h5
Shape final: (83119, 1917)
Actual: X35.h5
Shape final: (83131, 1917)
Actual: X36.h5
Shape final: (83143, 1917)
Actual: X37.h5
Shape final: (83572, 1917)
Actual: X38.h5
Shape final: (83584, 1917)
Actual: X39.h5
Shape final: (83596, 1917)
Actual: X4.h5
Shape final: (83877, 1917)
Actual: X40.h5
Shape final: (84719, 1917)
Actual: X41.h5
Shape final: (84731, 1917)
Actual: X42.h5
Shape final: (84743, 1917)
Actual: X43.h5
Shape final: (85936, 1917)
Actual: X44.h5
Shape final: (85948, 1917)
Actual: X45.h5
Shape final: (85960, 1917)
Actual: X46.h5
Shape final: (86267, 1917)
Actual: X47.h5
Shape final: (86279, 1917)
Actual: X48.h5
Shape final: (86291, 1917)
Actual: X49.h5
Shape final: (88430, 1917)
Actual: X5.h5
Shape final: (88442, 1917)
Actual: X50.h5
Shape final: (88454, 1917)
Actual: X51.h5
Shape final: (88466, 1917)
Actual: X52.h5
Shape final: (88568, 1917)
Actual: X53.h5
Shape final: (88580, 1917)
Actual: X54.h5
Shape final: (88592, 1917)
Actual: X55.h5
Shape final: (88837, 1917)
Actual: X56.h5
Shape final: (88849, 1917)
Actual: X57.h5
Shape final: (88861, 1917)
Actual: X58.h5
Shape final: (89707, 1917)
Actual: X59.h5
Shape final: (89719, 1917)
Actual: X6.h5
Shape final: (89731, 1917)
Actual: X60.h5
Shape final: (89743, 1917)
Actual: X61.h5
Shape final: (91060, 1917)
Actual: X62.h5
Shape final: (91072, 1917)
Actual: X63.h5
Shape final: (91084, 1917)
Actual: X64.h5
Shape final: (92583, 1917)
Actual: X65.h5
Shape final: (92595, 1917)
Actual: X66.h5
Shape final: (92607, 1917)
Actual: X67.h5
Shape final: (95179, 1917)
Actual: X68.h5
Shape final: (95191, 1917)
Actual: X69.h5
Shape final: (95203, 1917)
Actual: X7.h5
Shape final: (95385, 1917)
Actual: X70.h5
Shape final: (95429, 1917)
Actual: X71.h5
Shape final: (95441, 1917)
Actual: X72.h5
Shape final: (95453, 1917)
Actual: X73.h5
Shape final: (96282, 1917)
Actual: X74.h5
Shape final: (96294, 1917)
Actual: X75.h5
Shape final: (96306, 1917)
Actual: X76.h5
Shape final: (97152, 1917)
Actual: X77.h5
Shape final: (97164, 1917)
Actual: X78.h5
Shape final: (97176, 1917)
Actual: X79.h5
Shape final: (97201, 1917)
Actual: X8.h5
Shape final: (97213, 1917)
Actual: X80.h5
Shape final: (97225, 1917)
Actual: X81.h5
Shape final: (97237, 1917)
Actual: X82.h5
Shape final: (99433, 1917)
Actual: X83.h5
Shape final: (99445, 1917)
Actual: X84.h5
Shape final: (99457, 1917)
Actual: X85.h5
Shape final: (102787, 1917)
Actual: X86.h5
Shape final: (102799, 1917)
Actual: X87.h5
Shape final: (102811, 1917)
Actual: X88.h5
Shape final: (103054, 1917)
Actual: X89.h5
Shape final: (103066, 1917)
Actual: X9.h5
Shape final: (103078, 1917)
Actual: X90.h5
Shape final: (103090, 1917)
Actual: X91.h5
Shape final: (104458, 1917)
Actual: X92.h5
Shape final: (104470, 1917)
Actual: X93.h5
Shape final: (104482, 1917)
Actual: X94.h5
Shape final: (104754, 1917)
Actual: X95.h5
Shape final: (104766, 1917)
Actual: X96.h5
Shape final: (104778, 1917)
Actual: X97.h5
Shape final: (105025, 1917)
Actual: X98.h5
Shape final: (105037, 1917)
Actual: X99.h5
Shape final: (105049, 1917)

In [0]:
#format the date and sort the data
train_result_df['DATETIME'] = pd.to_datetime(train_result_df['DATETIME'], unit='s')
train_result_df = train_result_df.sort_values(['DATETIME'])
train_result_df.reset_index(drop=True,inplace=True)

In [0]:
#Check the result
print("Adapt start:", train_result_df['DATETIME'].min(), "Adapt end:", train_result_df['DATETIME'].max())
train_result_df.tail(5)

Adapt start: 2009-07-02 00:00:00 Adapt end: 2010-07-01 18:00:00

                  DATETIME           0           1    2  ...  1912  1913  1914  1915
105044 2010-07-01 17:40:00  318.059998  -82.980003  0.0  ...   0.0   0.0   0.0   0.0
105045 2010-07-01 17:45:00  312.109985  -91.480003  0.0  ...   0.0   0.0   0.0   0.0
105046 2010-07-01 17:50:00  299.309998 -102.099998  0.0  ...   0.0   0.0   0.0   0.0
105047 2010-07-01 17:55:00  295.839996 -100.650002  0.0  ...   0.0   0.0   0.0   0.0
105048 2010-07-01 18:00:00  298.510010 -101.330002  0.0  ...   0.0   0.0   0.0   0.0

[5 rows x 1917 columns]

### Concat the date from the 2 different source together

In [0]:
result_df = pd.concat([train_result_df,adapt_result_df])
result_df = result_df.sort_values(['DATETIME'])
result_df.reset_index(drop=True,inplace=True)

In [0]:
result_df.head(5)

             DATETIME          0           1  ...  1913  1914  1915
0 2009-07-02 00:00:00 -79.500000 -397.619995  ...   0.0   0.0   0.0
1 2009-07-02 00:05:00 -22.809999 -333.730011  ...   0.0   0.0   0.0
2 2009-07-02 00:10:00  23.020000 -301.720001  ...   0.0   0.0   0.0
3 2009-07-02 00:15:00  21.360001 -302.480011  ...   0.0   0.0   0.0
4 2009-07-02 00:20:00  25.180000 -299.279999  ...   0.0   0.0   0.0

[5 rows x 1917 columns]

In [0]:
# #save the concatenated data
# result_df.to_csv(output_path + 'concatenated_raw_data.csv',index=False,sep=';',decimal=',')

## 3. EDA
- Check missing values
- Check missing datetimes
- Check locations with only 0 value

### Check missing values

In [0]:
#Check missing values
print('Number of missing values:', result_df.isna().sum().sum())

Number of missing values: 0

### Check missing datetimes

In [0]:
#Check min and max datetime
print('MIN DATETIME:', result_df['DATETIME'].min())
print('MAX DATETIME:', result_df['DATETIME'].max())

MIN DATETIME: 2009-07-02 00:00:00
MAX DATETIME: 2010-09-25 22:15:00

NOTE: For the task, we only want to keep full days

In [0]:
#Drop the last not full day's data
result_df = result_df[result_df['DATETIME'] < datetime.datetime(2010,9,25,0,0,0)]
print('MIN DATE:', result_df['DATETIME'].min())
print('MAX DATE:', result_df['DATETIME'].max())

MIN DATE: 2009-07-02 00:00:00
MAX DATE: 2010-09-24 23:55:00

In [0]:
#Generate a datetimerange to find missing dates
control_datetimes = pd.date_range(
    start = result_df['DATETIME'].min(),
    end = result_df['DATETIME'].max(),
    freq = "5T"
)
control_datetimes_df = pd.DataFrame(control_datetimes,columns=['DATETIME'])
control_datetimes_df['CONTROL'] = 1
control_datetimes_df.head(5)

             DATETIME  CONTROL
0 2009-07-02 00:00:00        1
1 2009-07-02 00:05:00        1
2 2009-07-02 00:10:00        1
3 2009-07-02 00:15:00        1
4 2009-07-02 00:20:00        1

In [0]:
# merge the control datetimerange to the original and count the missing datetimes
check_datetime_df = control_datetimes_df.merge(
    result_df[['DATETIME']],
    on=['DATETIME'],
    how='left'
)
missing_datetimes = check_datetime_df.isna().sum().sum()
print(f"Missing datetime(s): {missing_datetimes}")

Missing datetime(s): 0

In [0]:
result_df = result_df[result_df.columns[:193]].copy(deep=True)
result_df

                  DATETIME           0  ...         190         191
0      2009-07-02 00:00:00  -79.500000  ... -597.289978  224.070007
1      2009-07-02 00:05:00  -22.809999  ... -634.650024  237.529999
2      2009-07-02 00:10:00   23.020000  ... -629.520020  238.410004
3      2009-07-02 00:15:00   21.360001  ... -613.169983  231.369995
4      2009-07-02 00:20:00   25.180000  ... -596.469971  227.899994
...                    ...         ...  ...         ...         ...
122683 2010-08-31 23:35:00  223.919998  ... -670.359985  494.630005
122684 2010-08-31 23:40:00  247.190002  ... -706.320007  548.700012
122685 2010-08-31 23:45:00  224.360001  ... -728.820007  592.390015
122686 2010-08-31 23:50:00  215.619995  ... -692.140015  562.690002
122687 2010-08-31 23:55:00  199.279999  ... -674.630005  554.789978

[122688 rows x 193 columns]

In [0]:
# Melt the dataframe to DATE-DATETIME-LOCATION-VALUE format
melted_result_df = pd.melt(result_df, id_vars=['DATETIME'],var_name='LOCATION', value_name='VALUE')
print(melted_result_df['DATETIME'].min(), melted_result_df['DATETIME'].max())
print(melted_result_df['LOCATION'].nunique())
melted_result_df.head(5)

2009-07-02 00:00:00 2010-08-31 23:55:00
192

             DATETIME LOCATION      VALUE
0 2009-07-02 00:00:00        0 -79.500000
1 2009-07-02 00:05:00        0 -22.809999
2 2009-07-02 00:10:00        0  23.020000
3 2009-07-02 00:15:00        0  21.360001
4 2009-07-02 00:20:00        0  25.180000

In [0]:
melted_result_df.to_csv(output_path + 'processed_data.csv',index=False)